---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ca-controller-for-strimzi.fullname" . }}
  labels:
    {{- include "ca-controller-for-strimzi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "ca-controller-for-strimzi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ca-controller-for-strimzi.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ca-controller-for-strimzi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $spec := .Values.env }}
            - name: {{ $key }}
              {{- toYaml $spec | nindent 14 }}
            {{- end }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- range $name, $spec := $.Values.volumes }}
            - name: {{ $name }}
              mountPath: {{ $spec.mountPath }}
            {{- end -}}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- range $name, $spec := $.Values.volumes }}
        - name: {{ $name }}
          {{- toYaml (omit $spec "mountPath") | nindent 10 }}
      {{ end -}}
