{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ca-controller-for-strimzi.fullname" . }}
  labels:
    {{- include "ca-controller-for-strimzi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ca-controller-for-strimzi.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ca-controller-for-strimzi.fullname" . }}
{{- end -}}
