name: Build image

on:
  push:
    branches: [main]
    tags: ['*']

permissions:
  contents: write
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: ghcr.io/sebastiangaiser/ca-controller-for-strimzi
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Setup ko
        uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - name: Login to GHCR
        run: ko login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          ko build --bare --tags=$(git describe --tags --always) .
